---
device: cuda:0
world_size: 2 
save-dir: './checkpoints/'
demo-dir: './results/'
name: "e3rf"
dataset_name: "seg_dataset"

seg_dataset:
  name: laboro
  train_root: './data/5.laboro_tomato/train/'
  test_root: './data/5.laboro_tomato/test/'
  train_annotation: './data/5.laboro_tomato/annotations/train.json'
  train_ids: './data/5.laboro_tomato/annotations/train.idx'
  test_annotation: './data/5.laboro_tomato/annotations/test.json'
  test_ids: './data/5.laboro_tomato/annotations/test.idx'


coco_dataset:
  name: coco_dataset
  train_root: '/data/jyp/coco/train2017/'
  test_root: '/data/jyp/coco/val2017/'
  train_annotation: '/data/jyp/coco/annotations/instances_train2017.json'
  test_annotation: '/data/jyp/coco/annotations/instances_val2017.json'
  train_ids: '/data/jyp/coco/train.idx'
  test_ids: '/data/jyp/coco/test.idx'

shapenet:
  name: shapenet
  obj:      '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/model_obj/models/'
  binvox:   '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/model_binvox/models-binvox-solid/'
  screen:   '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/model_screen/screenshots/'
  texture:  '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/model_texture/textures/'
  metadata: '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/metadata.csv'
  new_meta: '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/metadata_processed.csv'
  
backbone_out: 1024
base_channels: 32
vector_size : 1024

batch_size: 16

in_channels: 3
depth: 4

segmentation: e3rf
num_instance : 32
input_size : 32
num_class: 6
workers: 64
img_size: 256
split: 0.2
epochs: 100
lr: 0.001

lr_decay: 0.1
lr_decay_step: 10
gamma: 0.1 
momentum: 0.9
weight-decay: 0.00001
val_epoch: 10
save_epoch: 10

label-map:
  - background
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6

### 시각화 관련 설정
colorpallete: [
    0, 0, 0,
    255, 0, 0,
    0, 255, 0,
    0, 0, 255,
    255, 255, 0,
    255, 0, 255,
    0, 255, 255,
    255,255,255
]