shapenet:
  name: shapenet
  obj:      '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/model_obj/models/'
  binvox:   '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/model_binvox/models-binvox-solid/'
  screen:   '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/model_screen/screenshots/'
  texture:  '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/model_texture/textures/'
  metadata: '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/metadata.csv'
  metadata2: '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/metadata2.csv'
  metadata4: '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/metadata4.csv'

  new_meta: '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/metadata_processed.csv'
  rendered: '/data/jyp/farmbot.ai/2.shapenet/shapenetsem/'