---
checkpoints: ./checkpoints
pretrained: ./checkpoints/state_dicts

backbone: &backbone resnet18
dataset: &dataset cifar10
best_path: ./checkpoints/state_dicts/resnet18_cifar10_best.pth
save: ./checkpoints/state_dicts/resnet18_cifar10_best.pth

best: ./checkpoints/
backbone: resnet18
best_path: ${best}${backbone}_best.pth

dataset: 
  name: "cifar10" 
  root: "/home/jyp/data/cifar10"

dali: False 
data_dir:    "/home/jyp/data/imagenet/"
device: "cuda"
num_class :  10 
batch_size : 256 
workers :    4 
img_size :   32

timed:
  sample: 10000

set_gate:
  gates: 
    - 5 
  thresholds:
    - 0.15

lr: 0.001

backbone_training:
  epoch : 50 
  backbone_path: ""
  
branch_training:
  epoch : 30

branch:
  hidden: 8
  size: 8
