---
#### Basic Configuration ####
backbone: &backbone resnet18
dataset: &dataset cifar10

lr: 0.001
device: cuda:0
num_class :  10
batch_size : 256
workers :    16
img_size :   32

timed:
  sample: 10000

#### Backbone Training Configuration ####
backbone_training:
  epochs : 50 
  milestone:
    - 10
    - 20
    - 30
    - 40
    - 50
  gamma: 0.5

set_gate:
  gates:
    - 2
    - 6
  thresholds:
    - 0
    - 0

#### Branch Training Configuration ####
branch:
  hidden: 10
  size: 10
  threshold: 0.16

branch_training:
  epoch : 2
  lr: 0.001

#### Path Configuration ####
path: 
  root: &root ./
  checkpoints: &checkpoints checkpoints/
  backbone_folder: &backbone_folder backbone/
  model_folder: &model_folder state_dicts/ 
  confidence_folder: &confidence_folder confidence/
  performance_folder: &performance_folder performance/

performance_path:
  - *root
  - *checkpoints
  - *performance_folder

dataset_path: 
  - *root
  - data/
  - *dataset
  - /

backbone_path:
  - *root
  - *checkpoints
  - *backbone_folder
  - *backbone
  - _
  - *dataset
  - _
  - backbone.pth

model_path:
  - *root
  - *checkpoints
  - *model_folder
  - *backbone
  - _
  - *dataset
  - _
  - best.pth

csv_path:
  - *root
  - *checkpoints  
  - *confidence_folder