---
#### Basic Configuration ####
backbone: &backbone wide_resnet101_2
dataset: &dataset cifar10
num_exits: 4

lr: 0.0001
device: cuda:0
num_class :  10
batch_size : 128
workers :    6
img_size :   128
n_views : 2
timed:
  sample: 10000

#### Backbone Training Configuration ####
backbone_training:
  epochs : 30
  milestone:
    - 10
    - 20
    - 30
    - 40
    - 50
  gamma: 0.5

set_gate:
  gates:
    - 4
    - 8
  thresholds:
    - 0
    - 0

#### Branch Training Configuration ####
branch_training:
  epochs : 5
  lr: 0.0001

branch:
  hidden: 32
  channel: 32
  feature: 32
  size: 8
  threshold: 0.16
  feature: 100

contra:
  representation: 512
  hidden: 64
  projection: 16

  
branch_training:
  epoch : 30
  lr: 0.01

#### Path Configuration ####
path: 
  root: &root ./
  checkpoints: &checkpoints checkpoints/
  backbone_folder: &backbone_folder backbone/
  model_folder: &model_folder state_dicts/ 
  confidence_folder: &confidence_folder confidence/
  performance_folder: &performance_folder performance/
  mode: &mode ce_

combine_dir:
  performance_dir:
    - *root
    - *checkpoints
    - *performance_folder

  dataset_dir: 
    - *root
    - *checkpoints
    - data/
    - *dataset
    - /

  backbone_dir:
    - *root
    - *checkpoints
    - *backbone_folder

  model_dir:
    - *root
    - *checkpoints
    - *model_folder

  csv_dir:
    - *root
    - *checkpoints  
    - *confidence_folder

combine_path:
  backbone_path:
    - *root
    - *checkpoints
    - *backbone_folder
    - *backbone
    - _
    - *dataset
    - _
    - backbone.pth

  model_path:
    - *root
    - *checkpoints
    - *model_folder
    - *mode
    - *backbone
    - _
    - *dataset
    - _
    - model_best.pth

  model_name:
    - *mode
    - *backbone
    - _
    - *dataset
    - _
    - model_best.pth