---
pretrained: "./checkpoints/"
best: "./checkpoints/"
backbone: "resnet18"
dataset: "cifar10" 
dali: False 
data_dir:    "/home/jyp/data/imagenet/"
device: "cuda"
num_class :  10 
batch_size : 256 
workers :    4 
img_size :   32

timed:
  sample: 10000

set_gate:
  gates: 
    - 5
  thresholds:
    - 0.15

lr: 0.001

backbone_training:
  epoch : 50 
  
branch_training:
  epoch : 10

branch:
  hidden: 4
  size: 4
